export enum API {
   LOGIN = "login",
   LOGOUT = "logout",
   CAMPUSES = "campuses",
   ITEMS = "items",
   BINDINGS = "bindings",
   MENU = "menu",
   ORDERS = "user/orders",
   CAREERS = "careers",
   RELATIONS = "relations",
   COURSES = "/courses",
   MOVEMENTS = "/movements",
   USER = "/user",
   USERS_ADMINS = "/users/admins",
   USERS_STUDENTS = "/users/students",
   USERS_PROFESSORSHIPS = "/users/professorships",
   USERS_CAMPUS = "/users/campus",
   USERS_SCHOLARSHIPS = "/users/scholarships",

}
