export enum API {
   AVAILABLE_COPIES_RELOADER = "/available-copies-reloader",
   LOGIN = "login",
   LOGOUT = "logout",
   CAMPUSES = "campus",
   ITEMS = "items",
   PARAMETERS = "parameters",
   BINDINGS = "bindings",
   MENU = "menu",
   MY_ORDERS = "orders/me",
   ORDERS = "orders",
   FILES = "/files",
   CAREERS = "careers",
   RELATIONS = "relations",
   COURSES = "/courses",
   MOVEMENTS = "/movements",
   USER = "/user",
   USER_ADMIN = "/user/admin",
   USER_CAMPUS = "/user/campus",
   USER_PROFESSORSHIP = "/user/professorship",
   USER_SCHOLARSHIP = "/user/scholarship",
   USER_STUDENT = "/user/student",
   USERS = "/users",
   USERS_ADMINS = "/users/admins",
   USERS_STUDENTS = "/users/students",
   USERS_PROFESSORSHIPS = "/users/professorships",
   USERS_CAMPUS = "/users/campus",
   USERS_SCHOLARSHIPS = "/users/scholarships",
   USER_PARAMETERS = "/parameters/me",
   PRINTERS = "/printers",
   SERVER_STATUS = "/health/storage",
   ME= "/me"

}
