export enum MenuItems {
   HOME = "HOME",
   NEW_ORDER = "NEW_ORDER",
   MY_ORDERS = "MY_ORDERS",
   ACTIVE_ORDERS = "ACTIVE_ORDERS",
   HISTORICAL_ORDERS = "HISTORICAL_ORDERS",
   TRANSFER_MONEY = "TRANSFER_MONEY",
   MOVEMENTS = "MOVEMENTS",
   STUDENT_LIST = "STUDENT_LIST"
}
