export enum MenuItems {
   HOME = "HOME",
   NEW_ORDER = "NEW_ORDER",
   MY_ORDERS = "MY_ORDERS",
   ACTIVE_ORDERS = "ACTIVE_ORDERS",
   HISTORICAL_ORDERS = "HISTORICAL_ORDERS",
   TOP_UP = "TOP_UP",
   TRANSFER_MONEY = "TRANSFER_MONEY",
   MOVEMENTS = "MY_MOVEMENTS",
   MOVEMENTS_LIST = "MOVEMENTS_LIST",
   STUDENT_LIST = "STUDENT_LIST",

   COURSES = "COURSES",
   RELATIONS = "RELATIONS",
   CAREERS = "CAREERS",
   FILES = "FILES",
   PARAMETERS = "PARAMETERS",
   ITEMS = "ITEMS",
   BINDINGS = "BINDINGS",
   USERS = "USERS",
   CAMPUSES = "CAMPUSES"
}
